type: object
properties:
  version:
    type: string
  password_file:
    type: string
  jira_batch_size:
    type: integer
    minimum: 10
    maximum: 900
  templates_directory:
    type: string
  release_settings:
    type: array
    items:
      $ref: '#/$defs/releaseSettings'
required:
  - version
  - password_file
  - templates_directory
  - release_settings
$defs:
  releaseSettings:
    type: object
    properties:
      name:
        type: string
      url:
        type: string
        format: uri
        pattern: '^https?://'
      jql:
        type: string
      fields:
        type: array
        items:
          $ref: '#/$defs/fieldSettings'
        contains:
          type: object
          properties:
            type:
              const: file
      template:
        type: string
      ai_service:
        type: object
        items:
          $ref: '#$defs/aiServiceFields'
    required:
      - name
      - url
      - jql
      - template
  fieldSettings:
    properties:
      name:
        type: string
      type:
        type: string
        enum:
          - text
          - select
          - choice
          - editor
          - multiline
          - file
      message:
        type: string
      choices:
        type: array
        items:
          type: string
    required:
      - name
      - type
      - message
    if:
      properties:
        type:
          const: choice
    then:
      required:
        - choices
  aiServiceFields:
    properties:
      name:
        type: string
        enum:
          - chatgpt
          - gemini
          - copilot
      model:
        type: string
      prompt:
        type: string
